# Generated by Django 3.2.9 on 2022-02-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('p_category', models.CharField(max_length=100)),
                ('p_description', models.TextField(max_length=300)),
                ('p_quantity', models.PositiveIntegerField()),
                ('p_price', models.PositiveIntegerField()),
                ('p_image', models.ImageField(upload_to='product_img')),
            ],
        ),
    ]
