# Generated by Django 3.2.9 on 2022-02-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_image',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
    ]
