# Generated by Django 3.2.9 on 2022-02-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='products',
            table='product_tbl',
        ),
    ]
