# Generated by Django 3.2.9 on 2022-02-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=11)),
                ('date', models.DateTimeField()),
                ('address', models.DateTimeField()),
                ('pro_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.products')),
            ],
        ),
    ]
